In [3]:
from google.colab import files
uploaded= files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


In [5]:
import pandas as pd
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].value
y = dataset.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred = model.predict(X_test)

In [11]:
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [17]:
import numpy as np
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
ac = metrics.accuracy_score(y_test,y_pred)
precision=metrics.precision_score(y_test, y_pred)
recall=metrics.recall_score(y_test, y_pred)
f1_score=metrics.f1_score(y_test, y_pred)
print(ac)
print(precision)
print(recall)
print(f1_score)

[[55  3]
 [ 1 21]]
0.95
0.875
0.9545454545454546
0.9130434782608695


In [18]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 5, metric = 'manhattan', p = 2)
model.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan')

In [20]:
y_pred = model.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [21]:
import numpy as np
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
ac = metrics.accuracy_score(y_test,y_pred)
precision=metrics.precision_score(y_test, y_pred)
recall=metrics.recall_score(y_test, y_pred)
f1_score=metrics.f1_score(y_test, y_pred)
print(ac)
print(precision)
print(recall)
print(f1_score)

[[55  3]
 [ 1 21]]
0.95
0.875
0.9545454545454546
0.9130434782608695


In [22]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean', p = 2)
model.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [23]:
y_pred = model.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [24]:
import numpy as np
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
ac = metrics.accuracy_score(y_test,y_pred)
precision=metrics.precision_score(y_test, y_pred)
recall=metrics.recall_score(y_test, y_pred)
f1_score=metrics.f1_score(y_test, y_pred)
print(ac)
print(precision)
print(recall)
print(f1_score)

[[55  3]
 [ 1 21]]
0.95
0.875
0.9545454545454546
0.9130434782608695
